version: "3.1"
services:
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - /pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_MULTIPLE_DATABASES: roott
      POSTGRES_USER: roott
      POSTGRES_PASSWORD: roott
    restart: unless-stopped

  # pgadmin:
  #   image: dpage/pgadmin4
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "5555:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "nikasaih@gmail.com"
  #     PGADMIN_DEFAULT_PASSWORD: "roott"
  #   restart: unless-stopped
volumes:
  postgres-data:
